import 'package:divinecontrol/models/horoscope_models/horoscope_model.dart';
import 'package:divinecontrol/utils/app_images.dart';

List<HoroscopeModel> horoscopes=[
  HoroscopeModel(image: AppImages.aries, title: "Aries", todayDes: "You could be feeling a bit flush today, Aries, and therefore you might decide to do a little work on your house. This is more likely to be redecorating than any major repairs, as you're more into beauty right now than practical matters. Your aesthetic sense is very high, inspired from the higher realms, and therefore decorating decisions you make today are likely to be beautiful. Go to it!",
   yesterdayDes: "Some minor money matters may need to be handled today, Aries, and you might find this irritating as you probably have other things you'd rather do. The situation could cause some petty friction with family members, but that will pass. However, you'll be able to muster all your innate skills and get the money matters handled, which will leave the rest of the day to do what you want. Hang in there.",
    tomorrowDes: "Travel may cause more problems than it's worth today, Aries. You may forget some vital items when packing or there could be too little time to get everything ready. Your plane could be delayed or something valuable lost.Try to short-circuit potential problems. Use a checklist when packing, keep valuables close to you, and take lots of books and CDs in case you have to wait out a delay. In spite of it all, have fun!"),

HoroscopeModel(image: AppImages.taurus, title: "Taurus", yesterdayDes: "The healing of a temporary rift with your partner is likely to take place today, with a lot of honest communication and more apologies than are necessary. You might find that a lot of issues have come out in the open and that there is a new understanding between the two of you. A move could be coming up, Taurus, or at least changes within the household you have now.",
 todayDes: "You're feeling especially psychically and mystically inclined today, Taurus. You might want to read about such matters or attend a lecture or workshop given by someone in the field. Telepathic communications are coming your way. Don't be surprised if more than once during the course of the day you and another say the same thing at the same time. You might also experience a powerful kinship with people from the past.",
  tomorrowDes: "Finances may cause an upset between you and a friend today, Taurus. Perhaps this person owes you money and can't pay it back, or vice versa. If this is the case, try to work out some kind of arrangement that suits you both. There's always a way to create a win-win situation if you don't both get so angry that your objectivity is totally wiped out. Stay calm and focused and all should be well. Hang in there.")

,HoroscopeModel(image: AppImages.gemini, title: "Gemini", yesterdayDes: "The desire to go off by yourself and enjoy a little solitude is likely to be in conflict with the reality of your obligations today, Gemini. You could find yourself spacing out at times and unable to concentrate on any tasks at hand, so try to stay focused. Some irritating letters or phone calls could come your way, but nothing that you can't deal with. See an exciting movie tonight.",
 todayDes: "You're usually a very practical and down-to-Earth person, but today you may be more inclined than usual toward mysticism. Spiritual matters seem extremely appealing, and you could find yourself gravitating toward metaphysical bookstores or seeking discussions with people who are well versed in such matters. You also find your imagination working overtime. Indulge in a few flights of fancy, Gemini. We all need to escape from time to time!",
  tomorrowDes: "A social event could put you in touch with someone who's carrying around a lot of bitterness and anger, Gemini. This probably won't be very pleasant for you, as this person could well see you as the perfect listening post for all their problems. Don't feel trapped! Be polite but make your excuses as soon as you can. There are other friends present whose company you'll enjoy a lot more!"),

HoroscopeModel(image: AppImages.cancer, title: "Cancer", yesterdayDes: "Obligations to others could incline you toward staying home today, Leo, but important career issues could pull you in to work. This could cause some inner conflict, and you may have to face a choice. Only you can make that choice, but take care to be objective and take all the facts into consideration. Don't get yourself all emotionally worked up. This will only exacerbate the situation.",
 todayDes: "You're normally a very intuitive person, and today you may experience clairvoyance that could rival Jeane Dixon's. You could be feeling especially attuned to other planes, and your dreams are likely to be powerful and vivid. Use the messages you receive to inspire creative pursuits. Try your hand at painting, music, or poetry. You might not only be amazed by the results but learn even more from the work itself.",
  tomorrowDes: "You may have a wonderful day today, Leo. Your imagination, intuition, and creativity are all high, and inspiration for new artistic works could be filling your heart and brain. You'll be all too happy to discuss your ideas with anyone who shows an interest. The one dark spot in the day might be that a child, close friend, or lover goes into a snit because he or she feels ignored. Don't worry. They'll come out of it."),


HoroscopeModel(image: AppImages.leo, title: "Leo", yesterdayDes: "Don't expect any creative projects to go smoothly today, Cancer. You could experience mental blocks that you find difficult to get beyond. Don't let it get to you. The blocks will pass. Just put the project aside and get back to it later.A phone call from a friend might bring some disconcerting news that could cause you to want to pass it on to others. Before you do, make sure you have the facts straight.", 
todayDes: "Group activities involving meditation, psychic or spiritual topics, or artistic pursuits are probably very appealing to you right now, Cancer. This is the perfect day to start a class or attend a lecture on such subjects. You could meet some interesting people who become close friends. You're likely to feel a psychic bond with anyone you meet today, and you're likely to get the feeling that your life has changed for the better. Enjoy!", 
tomorrowDes: "The workplace could be very hectic today as a colleague prepares to leave on an important business trip, Cancer. Nerves could be strained and tempers short. Try to stay focused and get everything necessary done without making yourself crazy. You may be the one who keeps everyone else from going crazy, although you might consider hiding in the closet yourself. Say a prayer of thanks when your colleague finally rides off in the taxi.")

,HoroscopeModel(image: AppImages.virgo, title: "Virgo", yesterdayDes: "Today you're likely to feel torn in two different directions, Virgo. A part of you could want to sequester yourself somewhere and read, while another part of you feels that you should get out, go somewhere, and do something. You may be more impatient than usual with squabbles between colleagues or family members. It might be a good idea to do some exercise during the day to work off the inner tensions. Relax with a good book in the evening!",
 todayDes: "Your imagination is flying high today, Virgo. Your interest in mystical and metaphysical matters is at an all-time high, and you could find yourself strolling through New Age bookstores. Travel to distant places may seem especially appealing, and you might dream of flying to India, Israel, Egypt, or Ireland. This is all wonderful as long as you stay grounded. Plan a trip if you can. Join a meditation group. Go with the flow!",
  tomorrowDes: "Your home could be a very busy place today, Virgo. Visitors could come and go throughout the day, probably annoying you at times. You might also find yourself having to soothe angry outbursts on the part of a member of your household. Take care, however, that this person's problem doesn't get you so inflamed that you go into a fit of anger, too. Try to stay calm and focused and you'll get through the day.")

,HoroscopeModel(image: AppImages.libra, title: "Libra", yesterdayDes: "Minor difficulties over money could put you in a state of frustration. The problems aren't Earthshaking, but they still need to be handled and could take up a lot of time that you'd rather spend doing something else. Giving in to your frustration could waste more time than simply handling the situation and moving on, however. Try to keep your cool, Libra. Take your problems in both hands, resolve them, and move on.", 
todayDes: "Some wonderful news concerning money and career matters could come your way today, Libra. Your natural kindness and sympathy for others has led you to make some good friends who are also valuable business contacts. This is definitely paying off. Your aesthetic sense is at an all-time high, so this is a great day to start any creative projects that you have in mind. Success is definitely coming your way!", 
tomorrowDes: "Someone you work with might need a sympathetic shoulder to cry on today, Libra. Stresses on the job extend beyond everyone's capacity to endure, so don't be surprised if at some point a colleague sheds a few tears. You might find your patience pushed beyond its normal limits. On days like this it's best to work as quickly as you can, stay focused, and go for a drink after you leave work. Then have a nice walk home!")

,HoroscopeModel(image: AppImages.scorpion, title: "Scorpion", yesterdayDes: "An argument with your partner could have you feeling very disheartened and somewhat depressed today, Scorpio. Yet you probably are too shaken up to feel like discussing it with him or her. Spend the day keeping yourself busy and working off your frustration. Forget about it for a while, Scorpio. This should enable you to see the situation more objectively, so that you'll be in the proper frame of mind to kiss and make up when the evening comes.",
 todayDes: "A minor conflict with a romantic partner in the morning is likely to end with a tearful reunion and much reassurance by mid-afternoon. The end of the day could find the two of you planning a romantic trip abroad, even down to the restaurants you want to try! Discussions of spiritual or psychic matters could also bring you closer together. All in all, it's a tumultuous but romantic day.",
  tomorrowDes: "Children or possibly some close friends or a love interest could be upset today, Scorpio. The financial coffers aren't full enough to afford something they think they absolutely have to have right now. You might find yourself having to soothe their feelings, reassuring them that 'not now' doesn't necessarily mean 'never.' If they don't respond, don't keep pushing. They'll have to come to terms with the situation in their own way."),

HoroscopeModel(image: AppImages.sagittarius, title: "Sagittarius", yesterdayDes: "You might wake up this morning feeling a little less than your usual self, Sagittarius, and you might not be able to figure out why. There could be some sort of minor physical imbalance or you might be suffering from eyestrain. This could put you a little out of sorts with yourself and everyone else, particularly if you're stressed about work responsibilities. Avoid computers, if possible, and take time during the day to run or go for a brisk walk.",
 todayDes: "Your intuition, imagination, and insight have served you well on the job, and should pay off soon. A raise, commission, or perhaps a chance to invest in the company could be offered to you. Your self-esteem will definitely receive a boost! You might also find that you're growing even more intuitive than usual, and people are looking up to you because of it. Give yourself a pat on the back. You deserve it.",
  tomorrowDes: "Worry about a family member may be on your mind today, Sagittarius. This person could be all wrought up over work, money, or possibly a love affair that's broken off. Say whatever reassuring words you can muster, but don't expect him or her to respond, and don't fall into the trap of feeling that your kind words were all in vain. They did register. It's just going to take this person a while to come to terms with the situation."),

HoroscopeModel(image: AppImages.capricorn, title: "Capricorn", yesterdayDes: "Today, Capricorn, you might find yourself getting more irritated than you usually would at the quirks of friends, colleagues, partners, and children. Nerves could be frayed and tempers around you frazzled. At times like this it's best to remain centered and make the effort to be your usual warm and friendly self. No lasting rifts are likely to result, but tension with others can make for an uncomfortable day.", 
todayDes: "You can count on a very idyllic and romantic day today, Capricorn. You're feeling especially warm and sensual, and you tend to view the partner in your life through rose-colored glasses. He or she is very likely to regard you in the same way. If you've been longing for a dinner for two, complete with champagne, candlelight, and red roses, this is the day to go for it. And don't forget the violin music!",
 tomorrowDes: "Uneasy feelings may be plaguing you throughout the day, Capricorn. There could appear to be no valid reason for this. Everything seems to be going well for you, and no one close to you has anything heavy going on. It's probably nothing Earthshaking. You may just be intuitively picking up on the troubles and anxieties of people you pass on the street. Your intuition is high today, so you could psychically sense just about anything. Hang in there!"),


HoroscopeModel(image: AppImages.aquarius, title: "Aquarius", yesterdayDes: "Temporary difficulties at home might cause you to want to stay and resolve them rather than go to work or anywhere else. However, Aquarius, career matters may also be pressing, so you're likely to be in a bit of a quandary.At this time, the wisest decision is likely to be to take care of your personal life first. Professional matters will still be waiting for you tomorrow.", 
todayDes: "Someone who is a student of natural healing may come to visit you and share some ideas today. You tend to be interested in matters concerning health, and you might want to learn not only about herbs and nutrition but also spiritual healing. This is a good time to train your own healing abilities, Aquarius, as your sensitivity is high and you're more able than usual to tune in to the healing energies.", 
tomorrowDes: "A friend, perhaps a woman, could well be upset or even angry with you today, Aquarius. Money might be involved in some way. There may be nothing you can do to reassure her at this time, so it's best to give what reassurances you can and then back off. Whatever has gone wrong, she's probably overreacting, and eventually she'll see that. In the meantime, you do what you can to work off your own anxieties. Hang in there!"),

HoroscopeModel(image: AppImages.pisces, title: "Pisces", yesterdayDes: "Some rather unsettling communications could come your way today, perhaps from out of state. This isn't likely to be anything serious, Pisces, but it could be enough to put your nose a little out of joint. Changes in your neighborhood might interfere with your daily routine. A neighbor or relative could be ill and you might feel obligated to help them out a little. This is fine as long as you don't commit to too much.",
 todayDes: "Books and movies may inspire you to get involved in artistic activities. Your aesthetic sense is very high today, Pisces, and you may be drawing your inspiration from the higher realms. You might want to stroll through an art gallery or museum and try to sense the feelings of those from the past. A warm and loving letter or phone call could come from a romantic partner, elevating your mood even more. It's a very emotionally gratifying day.",
  tomorrowDes: "Is your boss a woman, Pisces? If so, stay out of her way today. To put it mildly, she isn't in a good mood. Work hard, be very sweet to everyone, and make copious use of your innate diplomacy. You may be on the receiving end of some sharp words, but by remaining focused and continuing your routine in your usual efficient manner, you should avoid any major blowups. Try to stay calm, and hope she goes home early!")

];