import 'package:divinecontrol/models/settings_models/settings_card_model.dart';
import 'package:divinecontrol/widgets/settings_widgets/custom_settings_question_card.dart';
import 'package:flutter/material.dart';
import 'package:flutter_settings_screens/flutter_settings_screens.dart';

class FaqsScreen extends StatefulWidget {
  const FaqsScreen({super.key});

  @override
  State<FaqsScreen> createState() => _FaqsScreenState();
}

class _FaqsScreenState extends State<FaqsScreen> {
  @override
  Widget build(BuildContext context) {
    return SettingsScreen(
      title: 'FAQs',
      children: [
        ...List.generate(questions.length, (index) => Padding(padding: const EdgeInsets.only(bottom: 10),child: CustomQuestionSettingsCard(cardModel: questions[index]),))

      ],
    );
  }
  final List<SettingsCardModel> questions=[
SettingsCardModel(title: "I am a New User, How can I sign up?", details: "You can sign up in 2 easy steps:\nStep 1- Enter the mobile number or gmail ID you want to register on Divine Connection.\nStep 2- Enter the OTP that you will receive on the email you entered to sign up.Once you have successfully signed up, you can fill in the required details and start consulting India's best Astrologers and Counselors.")
  ,SettingsCardModel(title: "How can I speak to an Astrologer or Counselor?", details: "First, sign up on the Divine Connection app by entering your mobile number. Your number will be verified using an OTP, which you will receive via email.Once you have signed up, you can talk to an Astrologer or Counselor in 3 easy steps:\nStep 1- Explore the various expert Astrologers and Counselors available on the Divine Connection platform. Select an Astrologer or Counselor based on experience, expertise, price, and the language of your choice.\nStep 2- Select a recharge pack and make payment.\nStep 3: Click on the call/chat icon to initiate a consultation with an Astrologer or Counselor. If the Astrologer or Counselor is busy, you can join the queue (Queuing option will be available after 3 recharges)."),
  SettingsCardModel(title: "What should I do if I am not receiving the OTP?", details: "If you are not receiving the OTP, please check the following things:\n• We request you to be in a strong network zone to receive the OTP.\n• We request you to use the correct Country/State code as per the number you want to log in/register with.\n• Please check that the number is active and you are receiving other messages on it.Meanwhile, you can log in via your registered email ID and password. If you are still not receiving the OTP, kindly write to us at the contact us option."),
  SettingsCardModel(title: "How can an Astrologer or Counselor help me?", details: "Divine Connection brings you a wide variety of experts who have expertise in various areas. When you consult a Vedic Astrologer or Counselor, they can analyze your birth chart and tell you the likely outcomes and possible course of action that you can take.They can give you a preview of what your life has planned for you. If facing difficulties, they can offer solutions. Tarot card readers will use tarot cards to guide you on the right path. Numerologists will rely on numbers related to your date of birth to offer you proper guidance and insight.They can help with baby names, business names, or other things where numbers play a role. Vastu experts here can help you with all your Vastu Shastra doubts and needs. The Feng Shui experts here can help you build a positively enhanced and balanced space so that you enjoy harmony and prosperity.Counselors have done Masters Degree and experienced in this Field. They are verified and giving the top notch advice.Our Prashna Kundali experts can answer all your questions about love, career, marriage, finance, and more. The KP astrology experts here can predict future events with accuracy. All in all, our experts can help you in multiple ways.However, please note that astrology consultation is not a replacement for any matter that requires medical or professional attention. (Refer to 'what questions I can ask', so you know what you can ask.)")
  ,SettingsCardModel(title: "For how long do I have to wait in Queue?", details: "When you join the queue of any Astrologer or Counselor, check the 'Queue Number', as it indicates the number you are placed at. You will also get to see the 'Wait time', which indicates the expected time in which you will get a call/chat request from that Astrologer or Counselor.\nFor example- If the wait time shows 10 minutes, you will get a call/chat request in approximately 10 minutes."),
  SettingsCardModel(title: "I am in the queue, and the Astrologer or Counselor is now offline. What should I do?", details: "If you are in a queue and the Astrologer or Counselor went offline, you don't have to worry as you are still in the queue. When the Astrologer or Counselor comes online again, you will get a call/chat request as per the same queue number you were placed at."),
 SettingsCardModel(title: "Do you have an App?", details: "Yes, you can download our 'DIVINE CONNECTION' App on Play Store and Apple Store."),
 SettingsCardModel(title: "Are the Astrologers and Counselors verified?", details: "Yes, all the Astrologers and Counselors on the Divine Connection platform go through a verification process. We verify the documents of all the Astrologers and Counselors, after which the Astrologers and Counselors go through a screening test. They also go through training sessions. All the experts here are verified and have relevant experience in their chosen areas of expertise."),
 SettingsCardModel(title: "Are all the Services and Features that are present and will be implemented in the future trusted and genuine?", details: "YES, you can trust each and everything which is present on our Website and App as they are Genuine. We have implemented the best AI technology to give you Accurate and 100 percent results but it's not the final decision about you. You can take it as an Advice and not the Final Interpretation and Decision.")
  ,SettingsCardModel(title: "Do Astrologers and Counselors know who they are talking to?", details: "No, the Astrologers and Counselors have no access to your phone number or address at any point. If you have shared your name, that is all they will know. Your Privacy is protected with us.")
  ,SettingsCardModel(title: "How do I pay?", details: "You can pay via -Credit / Debit card\nNetbanking\nWallet - Paytm, Google Pay, Phone Pay, Amazon Pay, etc.\nPaypal / Phone Pay (International users)"),
 SettingsCardModel(title: "Why am I unable to pay?", details: "If you are unable to pay, it could be because the payment gateway is inactive, or your card is not working. In either case, try using another card.")
 ,SettingsCardModel(title: "I have clicked on the Call/Chat button but I did not receive any Call/Chat. Why is that so?", details: "There are many reasons you may have made a call/chat request but have not received a call/chat. These could be:\n1. You are in a no network zone.\n2. Your chosen Astrologer or Counselor is in a no network zone.\n3. Your chosen Astrologer or Counselor has not received the call at their end.\n4. There may be an internet issue at the customer or the Astrologer's or Counselor's end if the call/chat request is not received.\n5. Please check your phone number in the My Account > Edit Profile > Personal details. Please ensure your mobile number is updated/verified.")
  ,SettingsCardModel(title: "I could not hear the Astrologer or Counselor but my balance was still deducted. Why is that so?", details: "This may occur due to poor connectivity or network loss at the customer or Astrologer's or Counselor's end. In case your balance was deducted for such a call where you were unable to communicate with the Astrologer or Counselor, please write to us at customercare@DivineConnection.com. We will refund the amount for all genuine cases. Also, please ensure you have good connectivity before making the call request."),
  SettingsCardModel(title: "I did not get any reply from the Astrologer or Counselor in the chat box but my balance was still deducted. Why is that so?", details: "This may occur due to poor connectivity or internet issue at the customer or Astrologer's or Counselor's end. In case your balance was deducted for such a chat where you were unable to communicate with the Astrologer or Counselor, please write to us at customercare@DivineConnection.com. We will refund the amount for all genuine cases."),
  SettingsCardModel(title: "When and how can I request a refund?", details: "If you cannot hear or there is excessive call drop or the Astrologer or Counselor takes a long time to respond or doesn't respond appropriately, or any other technical issue, you can request a refund by filling the Contact us form.")
  ,SettingsCardModel(title: "The call/chat dropped while I was talking. What should I do?", details: "Please check to see if your balance is over. If yes, just recharge and continue your call/chat. If not, click on the call/chat button once again, and you should get connected."),
  SettingsCardModel(title: "It is showing call in progress, but I am not on call. What should I do?", details: "If this happens, please fill the contact us form and we will resolve your issue at the earliest."),
  SettingsCardModel(title: "Can I delete my Account?", details: "Yes, you can delete but it will be difficult to open the account again so we advise that don't delete your Account."),
  SettingsCardModel(title: "Will I get a confirmation for the booked appointment?", details: "Yes. After successful payment, you will get an email and SMS with the confirmation and your appointment details. On the day of the appointment, you will get a reminder email and SMS."),
  SettingsCardModel(title: "Can I utilize my remaining minutes later?", details: "We would like to request you to utilize your entire appointment duration as the remaining minutes will neither be carried forward, refunded nor can they be claimed later.")
 ,SettingsCardModel(title: "Pooja will be Online ?", details: "Yes , Pooja will be Online. When the Pooja will be finished then we will end the meeting. Time is flexible for the meeting. It depends on the Pooja . We focus on quality first . As the Pooja is finished then we will end the meeting. We will schedule Pooja as per your time convenience.")
  ,SettingsCardModel(title: "Emotional Support services are available on Call ? ", details: "Yes , We will schedule counselling call and meeting as per your time convenience.\nYes , Emotional Support services means, Counselling. It is available on Call and online meeting .  When the call will be finished then we will end the meeting. Time is flexible for the meeting. It depends on the problem . We focus on quality first . As the call is finished then we will end the meeting. We will schedule a call as per your time convenience."),
  SettingsCardModel(title: "Astrology services are available on Call and Chat  ?", details: "Yes , We will schedule call and meeting as per your time convenience.\nYes , Astrology services are available on Call and online meeting .  When the call will be finished then we will end the meeting. Time is flexible for the meeting. It depends on the problem . We focus on quality first . As the call is finished then we will end the meeting. We will schedule a call as per your time convenience."),
 SettingsCardModel(title: "What if user don't agree the terms and conditions and misbehave in call or meeting ?", details: "For this kind of user, we are not responsible for his actions and we will take Strict Action will take against the user and he / she will be blacklisted for life time. We will cut the call immediately and money will not be refunded at any cost."),
  SettingsCardModel(title: "I want to ask another question apart from the above questions. Also I want to give feedback and I have found a bug.", details: "You can fill the / Contact us  / form and share the details. You can find / Contact us  / form at the End.")
  ];

}